[package]
name = "iced_wgpu_video"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { workspace = true, features = ["wgpu", "wgpu-bare", "tokio", "advanced"] }
iced_wgpu = { workspace = true }
ffmpeg-next = { workspace = true }
spin = { workspace = true }
bytemuck = { workspace = true }
glam = "0.33"
